export type Capitulo = {
  numero: number;
  titulo: string;
  subtitulo: string;
  /** Ilustração própria do capítulo. */
  imagem?: string;
  /** Índice da cena 3D de fundo, reaproveitando o mesmo sistema dos poemas. */
  cena: number;
  paragrafos: string[];
  /** Fragmento da profecia revelado ao final do capítulo — sem explicação. */
  fragmentoProfecia: string;
};

/** Arte de capa do livro (viajante diante do rosto de estrelas). */
export const IMAGEM_CAPA = "/assets/images/arelah-capa.webp";

export const capitulos: Capitulo[] = [
  {
    numero: 1,
    titulo: "Arelah — Origens",
    subtitulo: "O dia que nasceu o Infinito",
    imagem: "/assets/images/arelah-cap1.webp",
    cena: 2,
    paragrafos: [
      "Ela tinha um mundo só dela.",
      "A língua era diferente, os sons eram diferentes, e a magia existia mais forte nela do que na própria terra ao seu redor. O sol era quente porque Arelah era sorridente, a vida existia porque ela era feliz. Não era Arelah que ficava triste quando o mundo estava cinza — era o mundo que ficava cinza quando ela estava triste. Mas essa palavra nunca tinha entrado no vocabulário dela antes. Era só um mito. Até que um dia virou fato.",
      "Mas esse capítulo não é sobre isso.",
      "Talvez fosse sobre como Arquimendes conheceu Kassandra — não que alguém tivesse pedido pra contar, mas as histórias insistem em vir à tona quando menos se espera.",
      "Ele era um inventor sem inventos que funcionassem ainda, vivendo de promessas e resto de metal, quando a viu pela primeira vez: descalça, ajoelhada numa vala entre pedras, plantando algo que ninguém mais teria coragem de tocar. Ele perguntou o que era. Ela não respondeu — só olhou pra ele do jeito que olhava pras plantas, como quem decide, em silêncio, se vale a pena cuidar daquilo.",
      "Decidiu que valia.",
      "Ele voltou no dia seguinte com uma ferramenta que ela não tinha pedido. E no outro. E no outro, até virar hábito, e o hábito virar necessidade, e a necessidade virar a única coisa entre os dois que nunca precisou de explicação.",
      "Se amavam tão fervorosamente que os astros se alinhavam pra contemplar o ato — não porque alguém tivesse escrito isso em algum lugar, mas porque era simplesmente verdade, do jeito que certas verdades são, sem precisar de testemunha.",
      "Foi Kassandra quem trouxe a planta daquela mesma vala de pedras — anos antes, muito antes de Arelah, muito antes até do próprio Arquimendes. Ninguém mais se aproximava daquele lugar; diziam que era ruína de gente que não existia mais em nenhum mapa. Ela não perguntou por quê. Só cavou, embrulhou a raiz num pano úmido, e levou pra casa como quem resgata algo abandonado.",
      "A planta — ela chamava de sibannac, sem saber ao certo onde tinha aprendido o nome — florescia todo santo dia às 16:20, pegava fogo por conta própria, e se apagava sozinha minutos depois, deixando um cheiro que ninguém sabia descrever direito. Kassandra nunca perguntou por quê. Achava bonito demais pra questionar.",
      "Só sabia de uma coisa, sem saber explicar: perto da sibannac, era como se uma parte dela — aquela parte que sempre sentia as coisas antes de vê-las — ficasse em silêncio. Um silêncio bom, ela achava. Um descanso.",
      "Nunca soube que era outra coisa.",
      "Era 22 de setembro da era π. Ela completava 2 anos e 2 meses.",
      "Uma coincidência que ninguém naquela casa havia notado.",
      "Naquela noite, Arelah não falava. Só apontava coisas.",
      "Mas seus olhos estavam fixos na bolha d'água que pairava em pleno ar — rodando em torno de si mesma, lenta, perfeita, como um planeta minúsculo que havia decidido existir ali, entre a lareira e a mesa de jantar. Ela não sabia que aquilo era extraordinário. Pra ela era tão natural quanto respirar.",
      "Do outro lado da mesa, Arquimendes desenhava plantas de algo que provavelmente nunca seria construído. Kassandra organizava os potes sem olhar, como quem executa uma memória antiga.",
      "Ninguém via. Cada um no seu mundo — quando de repente.",
      "PLAAAAAAA.",
      "A porta bateu com uma força que não combinava com ninguém que quisesse apenas visitar. A bolha d'água desapareceu em poça no chão de terra batida. Arelah virou a cabeça devagar, sem susto — como se soubesse quem era antes de ver.",
      "Na entrada, com o cachimbo apagado entre os dentes e a muleta encostada na parede que acabara de estremecer, estava Barnabé.",
      "— Kassandra! — gritou ele, como se ela estivesse do outro lado de uma montanha. — A maldita planta floriu hoje? Preciso acender esse troço!",
      "Ninguém olhou pro chão.",
      "Ninguém viu a poça.",
      "Só Arelah — que apontou pra ela, depois apontou pra Barnabé, e fez algo que nunca havia feito antes.",
      "Sorriu.",
    ],
    fragmentoProfecia:
      "No dia em que o quatro encontrou o quatro, nasceu o que não tem fim. Ninguém contou os dias que passaram até ali. Ninguém precisava — o infinito não se soma, se repete.",
  },
  {
    numero: 2,
    titulo: "Arelah — Origens",
    subtitulo: "O Fim do Começo",
    imagem: "/assets/images/arelah-cap2-v2.webp",
    cena: 0,
    paragrafos: [
      "Barnabé entrou sem ser convidado — como sempre fazia.",
      "Mas o cachimbo continuava apagado. E a criança no chão não tirava os olhos dele desde que a porta batera — um jeito de olhar que ele não lembrava de ter visto antes, nem em campos de batalha.",
      "Kassandra, que não aceitava desaforos nem da própria sombra, cresceu como gigante em poderio. E antes de mais um passo, Barnabé — velho de guerra, sobrevivente de batalhas que ninguém mais lembrava — sentiu o frio na espinha. Entendeu, naquele instante, que desafiar aquela mulher era pior do que qualquer inimigo encontrado nos exércitos mais ferozes do passado.",
      "— Pare aí mesmo. Eu limpei a casa hoje — veja lá se isso são modos, seu ogro sem educação.",
      "Num instante, Barnabé perdeu toda a compostura. O velho de guerra encolheu como filhote de gatinho perto da lareira.",
      "— Sim, senhora dona Kassandra. Eu só queria mesmo saber se o foguinho deu certo. Estou precisando fumar. — Fez uma pausa, olhou pro chão, e apontou com a muleta. — Percebi que a senhora limpou a casa. Estava terminando de secar?",
      "Kassandra perdeu o tamanho gigantesco que a raiva lhe dera e se virou para a tal poça de água, olhando-a com uma ruga funda entre as sobrancelhas — de onde tinha vindo aquilo? Mas antes que o pensamento terminasse de se formar, uma máquina voadora mecânica cortou o ar vinda do quarto de Arquimendes, passou zunindo pela sala e foi se estatelar na parede do fundo.",
      "Kassandra olhou pra máquina. Olhou pra poça. Olhou pro quarto.",
      "Seu rosto ficou vermelho.",
      "— ARQUIMENDES, não acredito que você—",
      "— EUREKAAAAAAAAA!",
      "A voz dele explodiu antes que ela terminasse.",
      "Arquimendes saiu do quarto como se o mundo inteiro precisasse saber da notícia.",
      "— Finalizei! O coletor de partículas! Se eu estiver certo — e eu estou — com isso poderemos alimentar o gerador de energia para sempre!",
      "Kassandra respirou fundo. Pegou um pedaço de guantchale da mesa. Mordeu. Bocejou.",
      "— Claro, claro, claro. Só falta um pequeno detalhe, não é meu amor?",
      "— Qual?",
      "— Precisa funcionar.",
      "Arquimendes nem ouviu. Já tinha Barnabé pelo colarinho e o arrastava porta afora.",
      "— Venha, venha, venha — precisamos instalar no telhado. Agora.",
      "— Espere, espere — gritou Barnabé sendo arrastado — é mais seguro apoiar do outro lado, eu conheço estruturas, eu já vi casas—",
      "— Só segure a escada, seu velho falastrão.",
      "A casa de Arquimendes era um organismo vivo.",
      "Cabos percorriam as paredes como veias — entravam e saíam pelas raízes e frestas, carregando um fluxo de extratos de plantas escolhidos por Kassandra e energia gerada pelas engenhocas de Arquimendes. Cinco invenções fracassadas pra cada uma que funcionava. Sucata empilhada em cada canto. Papéis com anotações, sonhos e esquemas espalhados por todos os cômodos. Era impossível dizer onde terminava a casa e onde começavam as invenções.",
      "No centro de tudo isso — Arelah.",
      "Quieta. Observando. Rindo de coisas que ninguém mais via.",
      "Kassandra voltou com o balde, o pano e a água. Começou a limpar a poça de costas para a filha.",
      "Lá fora, Barnabé segurava a escada e discutia cada degrau enquanto Arquimendes subia escorregando, ignorando cada aviso com a confiança de quem nunca caiu — ainda.",
      "No topo, Arquimendes fez os últimos ajustes. Respirou fundo. Preparou-se para encaixar a peça final no capacitor translucidérico temporalmetildo convexso.",
      "Dentro, Arelah sentiu o vento.",
      "E o cheiro de chuva que ela tanto amava.",
      "O arrepio do clima a animou — ela também queria brincar na água. Lembrou da bolha. E instantaneamente, toda a água do balde de Kassandra voltou ao ar — rodando em torno de si mesma, perfeita, como um planeta que havia decidido existir ali de novo.",
      "Deu um gritinho tímido.",
      "— Alá.",
      "Kassandra sorriu sem virar.",
      "— Vai chover, minha princesinha. Está com fome?",
      "Virou-se devagar para ver a resposta da filha.",
      "E emudeceu.",
      "A cor saiu completamente do seu rosto.",
      "O silêncio durou exatamente o tempo de um raio decidir onde cair.",
      "KABLAN.",
      "O trovão cortou tudo ao mesmo tempo — o espanto de Kassandra, o grito de Barnabé lá fora, e o braço estendido de Arquimendes no momento exato em que encaixava a peça no capacitor.",
      "O raio o atingiu.",
      "A invenção conectou.",
      "Às 16:20, a sibannac floriu — e pegou fogo, como fazia todos os dias, naquele mesmo horário de sempre.",
      "A faísca encontrou os cabos. Os cabos encontraram os extratos. Os extratos encontraram a energia. A energia encontrou o raio. O raio encontrou a magia de Arelah no ar.",
      "E tudo — absolutamente tudo — se conectou na explosão.",
      "O tempo parou.",
      "Não desacelerou. Não hesitou.",
      "Parou.",
      "Barnabé congelou no meio de um grito. Kassandra congelou com a boca aberta e os olhos arregalados. Arquimendes congelou no telhado — iluminado, os cabelos em pé, uma expressão entre o êxtase e o terror.",
      "Só Arelah se movia.",
      "Atravessou a sala em câmera lentíssima — milissegundos que pareciam horas. Tocou os cacos que voavam sem chegar ao destino. Passou pelos fios de energia suspensa no ar como cortinas de luz. Cheirou a fumaça da sibannac que subia em espiral congelada.",
      "Para ela era um parque de diversões.",
      "Ela não sabia o que era uma explosão. Não sabia o que era o perigo. Não sabia o que era o tempo parando.",
      "Só sabia que aquelas cores eram bonitas. E que o cheiro de chuva ainda estava lá.",
      "Andou. Sorriu. Foi indo.",
      "Até chegar lá fora.",
      "E olhar.",
      "O cogumelo gigante de destruição subia lento e majestoso onde havia sido a sua casa — uma devastação completa, suspensa no tempo como uma pintura do fim do mundo.",
      "Arelah inclinou a cabeça.",
      "Apontou.",
      "E riu.",
    ],
    fragmentoProfecia:
      "O que parece o fim é só o começo, dobrado sobre si mesmo — como tudo que é infinito faz, quando alguém demora demais pra perceber que está olhando.",
  },
  {
    numero: 3,
    titulo: "Arelah — Origens",
    subtitulo: "Os Três Que Ficaram",
    imagem: "/assets/images/arelah-cap3.webp",
    cena: 1,
    paragrafos: [
      "O tempo levou um instante para lembrar como se mover.",
      "Não voltou de uma vez. Voltou em pedaços — primeiro o som, depois o cheiro, depois, por último, o peso das coisas que precisam cair.",
      "A nuvem em forma de cogumelo, que até então pairava congelada sobre os escombros, desabou sobre si mesma em silêncio, como se também estivesse exausta. Poeira. Fumaça. Um cheiro doce e queimado que não vinha só da madeira.",
      "Da sibannac, só restava cinza — e o que quer que aquela fumaça fizesse, já tinha feito.",
      "Barnabé foi o primeiro a se mexer — reflexo de quem passou a vida inteira aprendendo a se levantar antes de entender por quê.",
      "— Posição! — berrou, a voz rouca de comando, antes mesmo de abrir os olhos direito. — Todo mundo no chão, cabeça baixa, já!",
      "Ninguém se abaixou. Ele mesmo parou no meio do próprio grito, a muleta tremendo sob o peso, porque não fazia a menor ideia de que guerra estava tentando vencer, nem onde tinha aprendido a gritar daquele jeito.",
      "— Que... — murmurou, baixando o tom, olhando a própria mão como se ela pertencesse a outra pessoa. — Que diabos eu tava dizendo?",
      "Kassandra ergueu a cabeça da poça que limpava — ou tentava limpar, antes do mundo explodir — e cravou os olhos nele com a mesma dureza de sempre, quase por costume.",
      "— Fala baixo perto da criança.",
      "A ordem saiu antes de qualquer pensamento, pronta, como se sempre tivesse estado ali, só esperando pra ser usada. Barnabé fechou a boca na hora — e só depois os dois perceberam o que tinha acabado de acontecer: ela dera uma ordem a um homem cujo rosto mal reconhecia, e ele tinha obedecido sem questionar, do jeito que se obedece há anos.",
      "— Kassandra — disse ele, baixinho, testando o nome na boca como quem experimenta uma roupa emprestada. — É esse o seu nome, não é?",
      "— É. — Ela não perguntou como ele sabia. Sabia o dele também, Barnabé, sem lembrar de nenhuma conversa em que tivesse aprendido.",
      "Do que sobrou do telhado, Arquimendes escorregou mais do que desceu, aterrissando sentado no meio do entulho — e, antes de qualquer outra coisa, antes até de respirar fundo, esticou o braço pra examinar a própria mão chamuscada.",
      "— Fascinante — sussurrou, virando o pulso contra a luz. — A descarga passou pelo capacitor, pela planta, por mim... e eu continuo inteiro. Isso devia ser estudado.",
      "Só quando ergueu os olhos do próprio braço é que percebeu os outros dois olhando pra ele. E só então chegou a pergunta — atrasada, incômoda, maior que qualquer invenção: quem eram aquelas pessoas, e por que o peito doía de um jeito que não tinha nada a ver com física?",
      "— Eu... — começou, e não achou fim pra frase.",
      "— Arquimendes — disse Kassandra, antes que ele terminasse de não terminar. Não era pergunta.",
      "Ele assentiu, devagar, sem saber explicar por que aquele nome soava certo na boca dela, e estranho em qualquer outra.",
      "Os três ficaram ali, parados entre os escombros — três pessoas que se conheciam havia exatamente um minuto e meio, e que, ao mesmo tempo, carregavam entre si uma vida inteira que nenhum conseguia alcançar.",
      "Ninguém perguntou mais nada. Não havia pergunta que coubesse no tamanho daquele silêncio.",
      "Foi Arelah quem o quebrou.",
      "Sentada no meio do que sobrou do quintal, cercada de cacos e fumaça, ela esfregou os olhos como quem acorda de um cochilo comprido. Não parecia assustada. Parecia, se é que a palavra serve pra uma criança daquela idade, satisfeita.",
      "Os três adultos se viraram pra ela ao mesmo tempo.",
      "Foi Kassandra quem se moveu primeiro — não devagar, não com cautela, mas do jeito que se corre até quem se ama, sem pensar duas vezes. Ajoelhou na poeira ao lado da menina e passou a mão pelo cabelo dela antes mesmo de decidir fazer isso.",
      "— Você tá bem? — A voz saiu rachada, cheia de um carinho que não tinha explicação nenhuma pronta.",
      "Arelah só sorriu e apontou pra fumaça, como quem mostra um brinquedo novo.",
      "Arquimendes se aproximou mancando de leve, o cabelo ainda fumegando nas pontas, e abaixou até ficar da altura dela. Não disse nada sobre física dessa vez. Só olhou — com o mesmo espanto de quando tinha visto a descarga atravessar o próprio braço, só que maior.",
      "Barnabé ficou de pé, apoiado na muleta, um passo atrás dos outros dois. Vinha de uma vida inteira sabendo reconhecer a hora de recuar e deixar os outros chegarem perto — e sabia, sem saber como sabia, que aquele era um desses momentos.",
      "Mas também sabia outra coisa, mais funda que qualquer lembrança perdida: tinha acabado de ver aquela criança parar o tempo com as próprias mãos. Tinha visto ela devolver uma tempestade inteira pro céu de onde tinha vindo. E fosse o que fosse aquilo — soldado nenhum, por mais memória que tivesse perdido, ficaria de costas pra uma coisa daquele tamanho.",
      "Não porque fosse filha de alguém.",
      "Porque era ela.",
      "Ninguém falou sobre reconstruir a casa. Ninguém falou sobre nomes direito, sobre quem amava quem, sobre o que cada um tinha sido antes daquela noite. Isso viria depois, devagar, do jeito que se aprende uma língua nova: tentando, errando, repetindo.",
      "O que ficou decidido, sem que ninguém precisasse dizer em voz alta, foi mais simples que tudo isso: continuariam ali. Juntos. Por ela.",
      "Longe dali — muito mais longe do que qualquer um daqueles três conseguiria imaginar — o céu tinha se partido ao meio.",
      "Um feixe de luz sem cor definida cruzou a noite na direção contrária à de todas as estrelas, como se tivesse pressa de chegar a algum lugar que ainda não existia. Atravessou nuvens que não deviam estar ali. Acendeu, por um segundo e meio, três sóis que há eras não nasciam ao mesmo tempo. Dobrou uma tempestade inteira sobre si mesma e a jogou pra outro lugar — nenhum mapa registraria pra onde.",
      "A cinco constelações de distância, não houve um único olho, broto ou coração que não sentisse alguma coisa se mexer.",
      "Ninguém saberia dizer o quê. Ninguém saberia dizer de onde. Mas todos, de um jeito ou de outro, pararam o que estavam fazendo por um instante — e sentiram, fundo, que algo que não devia existir tinha acabado de nascer.",
      "Em algum lugar, alguém ergueu a cabeça.",
      "E começou a procurar.",
    ],
    fragmentoProfecia:
      "O que nasce do fim não escolhe os pais que lhe restam — escolhe quem fica. E quem fica, de um jeito ou de outro, será encontrado.",
  },
  {
    numero: 4,
    titulo: "Arelah — Origens",
    subtitulo: "A Casa de Três Tempos",
    imagem: "/assets/images/arelah-cap4.webp",
    cena: 0,
    paragrafos: [
      "Levaram vinte e três dias para o telhado voltar a ser telhado.",
      "Kassandra contava os dias em tábuas. Uma tábua pregada, um dia vivido — era o único calendário que ainda fazia sentido pra quem não tinha ontem pra comparar.",
      "A floresta em volta não perguntava nada. Ninguém passava por ali, ninguém via a fumaça, ninguém ouvia as marteladas. Era um esconderijo que nenhum deles tinha escolhido — e talvez por isso funcionasse.",
      "Arquimendes passou a primeira semana revirando os papéis que o fogo poupou. Eram dezenas: esquemas, cálculos, rabiscos nas margens, tudo numa letra apertada e nervosa que ele só reconhecia como sua porque não havia mais ninguém ali que escrevesse.",
      "— Esse sujeito é um gênio ou um idiota — anunciou, sacudindo uma folha no ar. — Ainda não decidi.",
      "— Decida enquanto carrega as vigas — respondeu Kassandra, sem erguer os olhos dos potes.",
      "Ele carregou. Mas à noite voltava aos papéis, lia as próprias ideias como quem escuta um desconhecido muito interessante, e discutia em voz baixa com a margem das folhas.",
      "Os potes, Kassandra nem precisava olhar. As mãos sabiam onde cada um morava — o de raízes à esquerda, o de sal no alto, o de cinzas azuis atrás — e se enganavam só quando a cabeça tentava ajudar. Descobriu depressa que funcionava melhor deixando de pensar.",
      "Da sibannac sobrara uma raiz. Escura, torta, enterrada no meio da cinza como se tivesse decidido esperar.",
      "Ela a replantou sem saber por quê. No terceiro dia veio um broto. No décimo, uma flor. E às 16:20 em ponto a flor pegou fogo sozinha, se apagou sozinha, e deixou aquele cheiro que ninguém sabia descrever.",
      "Kassandra anotou a hora num pedaço de casca. Depois anotou outra coisa, que não contou a ninguém: perto da planta, o zumbido que ela nem sabia carregar na cabeça ficava quieto. Um descanso.",
      "Nunca soube que era outra coisa.",
      "Barnabé, por sua vez, tinha decidido que não adiantava ficar sentado esperando uma lembrança chegar de visita.",
      "Levantava antes do sol, pendurava a muleta num galho e se plantava no meio da clareira — pés afastados, ombros baixos, o peso inteiro na terra. Não sabia por que aquela postura. Só sabia que o corpo ficava mais honesto assim.",
      "Depois vinham os movimentos. Um passo, uma virada, um golpe de braço que cortava o ar de um jeito que não era de lenhador. Lento no começo. Cada manhã um pouco menos lento.",
      "— O senhor sempre acordou com esse humor? — perguntou Kassandra uma vez, da porta, com a caneca na mão.",
      "— Não faço ideia, dona Kassandra. — Ele nem parou. — Mas esse tronco aqui me deve satisfações.",
      "Nenhum dos três perguntava por que treinava, estudava ou plantava. Faziam. Como quem arruma a casa antes da visita — sem saber quem vem.",
      "E no meio disso tudo, Arelah.",
      "Arelah apontava.",
      "Apontava pro balde, pro passarinho, pras mãos da mãe mexendo nos potes. E dizia a única palavra que tinha:",
      "— Alá.",
      "Alá pro fogo. Alá pro barulho do martelo. Alá pro vazio entre duas árvores, onde ninguém via nada. Era uma palavra que servia pra tudo, e talvez por isso ninguém duvidasse de que significava alguma coisa.",
      "Foi na segunda semana que aconteceu pela primeira vez.",
      "Ela estava sentada no chão da sala, diante da bacia de madeira onde a água esperava ser levada pro poço. Apontou. Disse seu alá, baixinho. E parou.",
      "Não dormiu. Não distraiu. Os olhos continuaram abertos, mas já não estavam ali — fixos em lugar nenhum, num ponto onde o mundo parecia dobrar.",
      "A bacia envelheceu.",
      "Os aros racharam, a madeira escureceu, o limo subiu pelas bordas como uma maré lenta. Em seguida desfez o caminho: o limo recuou, as rachaduras se fecharam, a madeira ficou clara e cheirando a serra recém-passada. Mais um instante e era só um tronco, depois só uma semente, depois — por um segundo que ninguém soube contar — nada.",
      "Então voltou a ser bacia.",
      "Kassandra ficou parada com o pano na mão. Arquimendes soltou o papel. Barnabé, na porta, esqueceu a muleta no ombro.",
      "— Ela fez isso — disse Arquimendes, baixinho, com a voz de quem vê o próprio invento funcionar sem ter apertado nada.",
      "— Ela está bem — disse Kassandra, e não era pergunta, era ordem para o universo.",
      "Arelah piscou. Voltou. Sorriu pros três, satisfeita, como quem acabou de ver um bicho bonito passar.",
      "— Alá — disse.",
      "Ninguém a repreendeu. Ninguém sequer pensou em repreender. Eles tinham visto o dia em que ela parou o tempo; uma bacia que ia e voltava parecia, comparada a isso, quase um jeito educado de brincar.",
      "O que sentiram foi outra coisa: a certeza de que aquilo precisava de cuidado, não de medo.",
      "— Ela não sabe o que está fazendo — observou Arquimendes.",
      "— Ninguém aqui sabe — rebateu Kassandra. — Então vamos descobrir juntos.",
      "Sentou-se no chão, na frente da menina, e pegou as mãozinhas dela entre as suas.",
      "— Respire comigo. Devagar. Não olhe pro nada, olhe pra mim. É pra mim que você aponta, tá? Aponta aqui.",
      "Arelah apontou o nariz da mãe, deu uma gargalhada, e a bacia atrás delas deu um estalo, só um, e ficou como estava.",
      "Kassandra olhou pros outros dois, vitoriosa.",
      "— Funcionou. Mais ou menos.",
      "— Em batalha — disse Barnabé, apoiando o peso na muleta — a gente aprende a segurar a espada sem apertar. Quem aperta, treme. Quem solta, perde. É um meio-termo, tipo segurar um passarinho.",
      "— Ela não tem espada — disse Arquimendes.",
      "— Tem o que tem — respondeu o ogro, dando de ombros que faziam sombra. — O princípio é o mesmo.",
      "Era um conselho que nenhum dos três sabia de onde vinha. Funcionava mesmo assim.",
      "Foi assim que a rotina mudou. De manhã Arquimendes ajeitava vigas e a menina o observava; à tarde, Barnabé ensinava a respirar, a soltar, a segurar um passarinho com a ponta da atenção; à noite, Kassandra sentava com ela perto da sibannac e esperava a flor pegar fogo, e a magia de Arelah ficava mansa, como bicho que dorme encostado em outro.",
      "E aos poucos a casa foi voltando.",
      "Mas voltando diferente.",
      "A parede norte subiu intacta, lisa, com o reboco que tinha antes da explosão — Arquimendes jurava nunca ter feito aquilo. A parede sul continuou do jeito que o fogo a deixara: escura, rachada, cheirando a fim. E a parede leste, a que não deveria existir ainda, apareceu certa manhã coberta de hera velha, com uma janela de moldura que nenhum deles tinha desenhado.",
      "— De quando é essa parede? — perguntou Kassandra, passando a mão na pedra fria.",
      "Ninguém soube responder.",
      "O passado, o presente e o que ainda estava por vir tinham se encontrado ali e decidido, de comum acordo, dividir o mesmo teto.",
      "Eles não se assustaram. Já não era possível se assustar de uma casa depois de ver o que se vira.",
      "Numa noite sem lua, quando a menina enfim dormia, Kassandra e Arquimendes ficaram sozinhos junto ao fogo. Sentados perto demais, longe demais, sem saber qual dos dois.",
      "— Eu não sei se eu amava você — disse ela, olhando as brasas. — Queria dizer isso em voz alta, só pra não carregar sozinha.",
      "— Eu também não sei — respondeu ele, sem ofensa nenhuma, com a mesma curiosidade com que lia seus esquemas. — Mas sei que, se você saísse por aquela porta, eu iria atrás.",
      "— Isso não é amor. Pode ser dever.",
      "— Pode ser. — Ele sorriu, torto. — Mas se eu não lembrasse de nada, eu iria atrás de você sempre!",
      "Ela não respondeu. Mas não se afastou.",
      "Lá fora, na clareira, Barnabé fazia a última ronda da noite, a muleta pendurada, o passo mais firme do que o de alguém que não se lembrava de por que andava assim.",
      "Não sabia ainda — nenhum deles sabia — que cada manhã de treino o preparava para um dia que se aproximava de passos lentos, e que esse dia exigiria dele muito mais do que postura.",
      "Longe dali — longe o bastante para que o vento esquecesse o nome de quem soprava — algo parou no meio de uma estrada.",
      "Sentiu.",
      "Foi pouco. Uma dobra de ar. Um eco de bacia que envelhece e rejuvenesce no mesmo instante. Mas era o bastante: pela primeira vez desde a noite em que o céu se partira, o rumo deixou de ser um palpite e virou um cheiro.",
      "Cada magia que a menina fazia acendia uma luzinha. E cada luzinha era um pouco mais fácil de seguir do que a anterior.",
      "Atrás da casa de três tempos, no escuro, uma criança dormia com um sorriso pequeno, e na boca, mesmo no sono, a única palavra que sabia:",
      "— Alá.",
    ],
    fragmentoProfecia:
      "Quem dobra o tempo não o esconde — deixa dobras. E toda dobra é um caminho, para quem souber seguir o vinco.",
  },
  {
    numero: 5,
    titulo: "Arelah — Origens",
    subtitulo: "A Guerra de Dentro",
    imagem: "/assets/images/arelah-cap5.webp",
    cena: 2,
    paragrafos: [
      "Arelah era uma menina alegre e mimada.",
      "Tinha três adultos girando em volta dela como luas — um ensinando, outro repreendendo, uma amando, e os três, às vezes, tudo ao mesmo tempo. Não conhecia o silêncio. Quando precisava de alguma coisa, apontava. Quando precisava de tudo, dizia:",
      "— Alá.",
      "E alguém vinha.",
      "Mas a casa de três tempos tinha começado a ficar pesada de coisas não ditas, e as crianças sentem esse peso antes dos adultos.",
      "Barnabé tentou treinar de todas as formas.",
      "Só que o corpo de um ogro velho tem memória própria, e a dele estava cobrando as dívidas de uma vida inteira. O joelho estalava. O ombro travava no meio do golpe. A cabeça sabia exatamente o que fazer — o pé direito aqui, o quadril ali, o peso descendo como uma pedra num poço — e o corpo respondia com um atraso humilhante, como um criado surdo.",
      "Numa manhã, depois de cair sentado pela terceira vez diante do mesmo tronco, ele ficou no chão, ofegante, olhando as próprias mãos.",
      "— Se o corpo não vai — resmungou —, a cabeça vai na frente.",
      "Sentou de pernas cruzadas, fechou os olhos e treinou ali mesmo. Por dentro.",
      "Na imaginação, os joelhos eram novos. O tronco virava um exército inteiro, e ele o atravessava sem pressa, golpe por golpe, errando de propósito para aprender, repetindo até a repetição virar instinto.",
      "A cada sessão ficava mais hábil. E um dia, no meio do exército imaginário, o ar dentro dele se encheu de uma coisa que não era respiração — e ele soltou, lá dentro, um grito.",
      "Não de dor, nem de medo. Um grito de guerra antigo, rasgado, que subiu pelo peito como um incêndio e calou todo o exército de uma vez. Naquele instante, na cabeça dele, era imparável. Os golpes não doíam, o cansaço não chegava, o mundo inteiro cabia num único passo para frente.",
      "Durou alguns minutos. Quando abriu os olhos, estava suando, tremendo e sorrindo — um sorriso feio, de presas, que ninguém viu.",
      "Tentou de novo no dia seguinte. E no outro. Ainda era só imaginação. Mas imaginação treinada demais costuma esquecer que é imaginação.",
      "Arelah, de longe, passou a sentar na frente dele de pernas cruzadas, olhos apertados com toda a força, fingindo meditar. Durava dois segundos. Depois espiava com um olho só, para conferir se ele tinha visto.",
      "Kassandra, por sua vez, já estava inteira dentro da própria cabeça.",
      "Sabia as plantas, os potes, as raízes, as doses. Cada vidro era uma frase de uma língua que as mãos falavam sem esforço — e quanto mais ela falava, mais sentia que existia uma língua maior por trás dessa, onde alguma coisa importante tinha sido dita.",
      "Foi isso que a levou ao pote do fundo.",
      "O de cinzas azuis, aquele atrás de todos, que as mãos sempre contornavam sem que a cabeça perguntasse por quê. Dessa vez ela perguntou. Pegou uma pitada com a ponta do dedo, cheirou, hesitou, provou.",
      "Nada. Gosto de metal e de chuva velha. Anotou numa casca: sem efeito aparente.",
      "Foi uma anotação errada.",
      "Passou o resto do dia calada. Cortou raízes sem olhar, pregou tábuas sem falar. À tarde a sibannac floriu e pegou fogo, e pela primeira vez Kassandra não se aproximou. Ficou na porta, de costas, com as mãos na cabeça, como quem tenta calar um zumbido que não tinha antes.",
      "Perto da hora do jantar, Arquimendes entrou animado, com um papel na mão, falando de uma ideia sobre cabos e raízes. Ela o encarou como se o visse pela primeira vez — e não gostasse.",
      "— Você sabia — disse, baixo.",
      "— Sabia o quê?",
      "— Não se faça de bobo. Você sempre soube. — A voz foi subindo. — Você me deixou sozinha naquela noite. Disse que voltava e não voltou. Foi você que trouxe eles até aqui!",
      "— Kassandra, nenhum de nós se lembra de nada, como é que eu poderia—",
      "— Cala a boca! Você nunca ouve! Todas as vezes, todas as vezes foi assim!",
      "Não havia todas as vezes. Não havia noite nenhuma, não havia promessa, não havia ninguém que tivesse sido trazido. Os dois sabiam disso. E sabiam também que ela falava com a convicção de quem lembra de cada detalhe.",
      "Era isso que mais assustava Arquimendes: não a fúria, mas a precisão. E se fosse verdade? E se ela, de todos, tivesse lembrado primeiro? E se ele fosse mesmo o homem que ela descrevia?",
      "Na porta, a muleta no ombro, Barnabé tentou:",
      "— Dona Kassandra...",
      "— Não me chama de dona! — ela gritou, e o ogro, que já tinha visto exércitos, recuou meio passo.",
      "Então algo cedeu. Os olhos dela se encheram, e a raiva desabou inteira, sem avisar, como parede de casa velha. Mas ela não voltou atrás.",
      "Foi até o berço onde Arelah acordara com o barulho. Ajoelhou. Beijou-lhe a testa, as duas mãos, a testa de novo.",
      "— Me perdoa — sussurrou.",
      "— Alá — disse a menina, e apontou as lágrimas da mãe. Pela primeira vez na vida, apontou para alguém e não riu.",
      "Kassandra levantou, passou pela porta e entrou na floresta. Ninguém a segurou. Barnabé deu um passo, Arquimendes ergueu a mão, e nenhum dos dois soube com que direito impediria quem escolhe ir.",
      "Na mesa, o pote de cinzas azuis continuava aberto. Na casca ao lado, a anotação: sem efeito aparente.",
      "Ninguém soube o que tinha acontecido. Ninguém soube dizer se ela fugia deles — ou de alguma coisa que só ela ouvia.",
      "Naquela noite a casa ficou grande demais.",
      "Barnabé saiu para a clareira, de guarda, na esperança de ouvir passos voltando. Arquimendes olhava o fogo sem ver. E Arelah, que nunca tinha ficado só em toda a vida, conheceu sua primeira solidão deitada no berço, de olhos abertos.",
      "Apontou para a escuridão do teto. Disse seu alá, baixinho, sem esperar que alguém viesse.",
      "E partiu.",
      "Não viu o berço, nem a casa, nem o teto de três tempos. Os olhos continuaram abertos, só que para dentro. A bacia de madeira, na sala, nem estremeceu — dessa vez a magia não tocou o mundo. Foi para outro lugar.",
      "Primeiro veio a floresta. A mesma de fora, mas vista de longe, de cima, com um escuro que parecia respirar.",
      "E então ela viu.",
      "Algo se movia entre as sombras.",
      "Rápido. Esgueirando-se de tronco em tronco, de sombra em sombra, sem ruído, sem cansaço. Faminto — ela soube que era faminto antes de saber que sabia. Não tinha silhueta, não tinha forma, não tinha rosto. Era menos um corpo do que uma presença: uma falta de luz que andava sozinha.",
      "Não era hostil de tudo. Era hostil de um jeito conhecido, o jeito de uma coisa que já esteve dentro de casa. Arelah não sabia explicar por que sentia isso. Só sabia que aquilo, se tivesse olhos, já a reconheceria.",
      "Quando a visão estava inteira diante dela, algo se acendeu.",
      "Um feixe. Fino, tênue, um fio de luz tão delicado que parecia desenhado com um cabelo, riscando a noite a partir de algum lugar. Um rastro. A sombra o viu — ou o farejou — e foi atrás.",
      "Atravessou vales em silêncio. Subiu pelo cume das árvores sem balançar um galho. Cruzou rios sem molhar o escuro que carregava, escalou montanhas em linha reta, ignorando caminhos. E quando a montanha não deixou passar, entrou nela — desceu por dentro da própria terra, pela pedra, pelas raízes, pelas veias de água escondidas, sem parar um instante.",
      "Incansável.",
      "E Arelah, no meio da visão, reconheceu a luz. Era a luz que ela fazia quando apontava. Era a bacia que envelhecia. Cada alá que tinha dito era um ponto, e a linha toda era feita de pontos.",
      "A cada ponto, a sombra chegava um pouco mais perto.",
      "Ela quis dizer alguma coisa, e a visão não deixou. Quis fechar os olhos, e descobriu que já estavam fechados.",
      "A casa de três tempos apareceu no fim da linha, pequena, quente, com a janela acesa. Dentro, duas silhuetas. E uma cadeira vazia.",
      "Na borda da clareira, no escuro, a sombra parou.",
      "Estava longe ainda — dias, talvez, ou meses, ou nenhum, a visão não sabia contar. Ficou imóvel, como quem espera. Como quem sabe que esperar também é caçar.",
      "Depois virou, sem ter rosto, para onde Arelah estava.",
      "E a olhou.",
      "Não tinha olhos. Olhou assim mesmo.",
      "Arelah voltou com um soluço. Pela primeira vez na vida chorou sem ser por fome, nem por manha: chorou como choram os adultos, calada, com a garganta inteira.",
      "Foi o choro mudo que chamou Barnabé, não o barulho. Ele entrou na casa em passos que o joelho não aprovava, e a encontrou sentada no berço, apontando a janela escura.",
      "— Alá — disse ela.",
      "Barnabé já tinha ouvido aquela palavra cem vezes. Nunca daquele jeito. Pela primeira vez, alá não era um pedido nem uma alegria.",
      "Era um aviso.",
      "Ele fechou a mão no cabo da muleta como quem fecha o punho numa espada — e, pela primeira vez em muito tempo, não precisou pensar em como segurar.",
    ],
    fragmentoProfecia:
      "O que não tem nome não pode ser chamado, mas pode chamar. E toda luz, mesmo a mais fina, é um fio que alguém, do outro lado, aprende a puxar.",
  },
  {
    numero: 6,
    titulo: "Arelah — Origens",
    subtitulo: "Katecói",
    imagem: "/assets/images/arelah-cap6.webp",
    cena: 1,
    paragrafos: [
      "Os pássaros pararam primeiro.",
      "Não foi um silêncio de pausa. Foi um silêncio de coisa que prende a respiração: o vento deixou de passar entre as folhas, os insetos deixaram de zunir, e até a sibannac demorou um segundo a mais para pegar fogo naquela tarde.",
      "Fazia nove dias que Kassandra tinha ido embora. A cadeira dela continuava vazia à mesa, e ninguém a puxava, ninguém a movia, como se mexer nela fosse admitir alguma coisa.",
      "Arelah levantou a cabeça do prato, apontou para a borda da clareira e disse, baixinho, o mesmo alá do aviso.",
      "Barnabé já estava de pé. Fazia nove noites que dormia sentado, com a muleta na mão.",
      "— Entra — disse a Arquimendes. — Tranca a porta. Fica com ela.",
      "— Eu estou terminando uma coisa — respondeu o inventor, já enrolando um embrulho comprido num pano. — Duas, na verdade. Não saia daí até eu—",
      "— Não vou esperar o senhor terminar coisa nenhuma — disse o ogro, e foi, com a muleta batendo na terra como um coração lento.",
      "Plantou-se no meio da clareira. Pés afastados, ombros baixos, o peso inteiro na terra. A postura de todas as manhãs.",
      "A sombra não chegou. Foi aparecendo.",
      "Primeiro o escuro entre dois troncos ficou mais espesso. Depois as árvores perderam as bordas, como se alguém as tivesse desenhado a lápis e começasse a apagar. Depois não havia mais árvores naquele pedaço da floresta: só uma falta, do tamanho de um homem, e de dois, e de três.",
      "— Eu não sei quem você é — disse Barnabé para a escuridão. — Mas daqui você não passa.",
      "Sombras não respondem. Elas acontecem.",
      "Ela veio.",
      "O primeiro golpe da muleta atravessou o escuro sem encontrar nada e voltou gelado. O segundo também. O terceiro encontrou — e a sombra se fechou em volta do braço dele como uma boca.",
      "O frio entrou por dentro. Não era frio de inverno: era um frio de esquecimento, que apagava a força do punho, dedo por dedo.",
      "Ele rugiu e bateu de novo. Bateu com tudo que tinha: com o joelho que estalava, com a cadeira vazia, com o corpo que o traíra de manhã e de tarde. Bateu de raiva. E a sombra, a cada golpe, ficou um pouco maior.",
      "Ele não percebeu. Estava ocupado demais sendo furioso.",
      "O corpo respondia com atraso, como sempre. A sombra não. Atingiu-o no peito, e o ogro voou dois passos, bateu contra um tronco e escorregou até o chão. A muleta partiu-se em duas.",
      "Tentou o grito. Aquele, o de dentro, o que na imaginação tinha feito um exército inteiro se calar.",
      "Saiu tosse.",
      "A cabeça sabia. O corpo, mais uma vez, não.",
      "Barnabé ficou de joelhos, de mãos na terra, a respiração cheia de pedras. Levantou os olhos, e a sombra já não olhava para ele.",
      "Olhava para a casa.",
      "Passou por cima dele como quem passa por um tapete.",
      "Na porta, Arquimendes apareceu com Arelah atrás de si e, nas mãos, a invenção em que vinha trabalhando — uma gaiola de fios e cristais ainda sem nome, ligada por cabos grossos ao que restara do coletor de partículas.",
      "— Isso devia funcionar — murmurou, apontando-a para o escuro. — Teoricamente. Em algum universo.",
      "Girou a manivela.",
      "A gaiola acendeu, e uma rede de luz fria cruzou a clareira e prendeu a sombra no ar. Ela se debateu. A luz estalou. Arquimendes firmou os pés, mordeu o lábio, e por quatro segundos inteiros a invenção funcionou.",
      "Foi nesse intervalo que Arelah saiu de trás dele.",
      "Não correu. Andou, devagar, até a beira do degrau, e olhou para o fim da clareira onde o ogro estava caído: ferido, de joelhos, sem muleta e sem fôlego, com o rosto de quem já escolheu perder e só está esperando alguém avisar.",
      "Ela o apontou.",
      "E gritou — a voz fina de criança, rachada de tão alta, uma palavra que nunca tinha dito, que ninguém sabia que ela trazia:",
      "— KATECÓI!",
      "O tempo saiu de dentro do ogro.",
      "Não de uma vez. Primeiro, o grisalho da barba recuou, como maré. Depois as cicatrizes se fecharam uma a uma, e as marcas de cansaço que tinham levado cem anos para chegar foram embora num instante. As costas se endireitaram. Os ombros, que estavam caídos, cresceram até quase rasgar o colete. Os braços incharam, as veias subiram, o joelho que estalava estalou pela última vez e se calou.",
      "A muleta quebrada, caída no chão, envelheceu de uma vez: virou pó, virou terra, virou nada. Era para lá que o tempo tinha ido.",
      "Barnabé levantou.",
      "Já não parecia um velho. Parecia o que sempre fora, no começo: um ogro em plenitude, enorme, musculoso, letal. Os olhos amarelos acenderam.",
      "Ele olhou para as próprias mãos.",
      "Depois abriu a boca e soltou o grito.",
      "Não era o da imaginação. Era maior. Subiu do peito como um incêndio, atravessou a clareira, rolou pela floresta como um trovão deitado, e fez cada folha da copa tremer de uma só vez.",
      "Tudo o que o ouviu perdeu a vontade de lutar.",
      "Os pássaros caíram dos galhos e ficaram parados no chão. Uma raposa congelou com a pata no ar. O vento esqueceu de soprar. Arquimendes ficou imóvel, de olhos arregalados, com a manivela da gaiola ainda na mão, e o embrulho de pano que trazia debaixo do braço escorregou e caiu aos pés do ogro.",
      "O medo parou todo mundo.",
      "Menos a sombra.",
      "Ela arrebentou a rede de luz como quem rasga uma teia, destruiu a gaiola num estalo de cristais, e se virou devagar para o ogro.",
      "Barnabé abaixou os olhos para o embrulho.",
      "O pano tinha se aberto na queda. Dentro, uma espada.",
      "Não era de ferro. A lâmina parecia feita de madrugada: um fio de luz pálida, atravessado por engrenagens minúsculas e raízes finas que brilhavam por dentro, e que cantava, baixinho, um zumbido que cheirava a chuva. No cabo, entalhada com a letra firme de quem comanda potes, uma frase: segura sem apertar. E embaixo, quase invisível, um desenho minúsculo de um cachimbo aceso.",
      "Fora feita a duas mãos, nas noites em que os dois achavam que ninguém via. Antes da briga. Antes da floresta engolir uma delas.",
      "Ele a pegou.",
      "A espada pesava menos que o ar, e ele sentiu o peso inteiro do mundo.",
      "— Muito bem — disse Barnabé.",
      "E foi.",
      "O primeiro golpe foi tão rápido que o som chegou depois. A lâmina atravessou a sombra de cima a baixo e deixou uma linha de luz dentro dela, como uma ferida que não sangra. O escuro gritou — um grito sem som, que fez os dentes de Arquimendes doerem.",
      "A sombra se partiu em dez. Em vinte. Cada pedaço ganhou quatro patas, um focinho sem rosto e uma fome do tamanho de uma floresta. Uma alcateia inteira de escuro saltou ao mesmo tempo.",
      "O ogro girou. A espada desenhou um círculo de luz em volta dele e a primeira onda de lobos se desfez em fumaça. Ele pulou para o tronco mais próximo, usou-o de trampolim, caiu no meio do bando com os dois pés e a lâmina para baixo, e a clareira inteira se acendeu como se o dia tivesse voltado por um segundo.",
      "Cortou, esquivou, rugiu. O grito voltou e os lobos que o ouviram recuaram, tremendo, e os que não recuaram foram cortados ao meio. Ele era uma tempestade com músculos. Era a guerra inteira que o corpo sabia e nunca pudera dizer.",
      "A alcateia se juntou de novo, em volta de um só corpo. A sombra voltou a ser uma.",
      "E era maior.",
      "Ele percebeu antes que quisesse. Cada golpe que dera, cada corte, cada rugido de raiva, tinha ido parar dentro dela. Quanto mais ele a odiava, mais ela crescia: já tapava metade do céu, e as copas das árvores ao redor tinham ficado cinzas, sem folha.",
      "Ela avançou. Ele a cortou. Ela cresceu.",
      "Ele a cortou de novo. Ela cresceu.",
      "Barnabé recuou um passo, suando, o peito subindo e descendo. A espada tremia na mão. O minuto passava — ele sentia: o tempo que Arelah lhe tirara pesava no peito como um empréstimo, e o grito, o corpo, a plenitude, tudo isso acabava.",
      "Olhou para a sombra.",
      "E, pela primeira vez, olhou de verdade.",
      "Não viu rosto. Mas viu o que ela era feita: o rancor de quem foi abandonado. A raiva de quem não entende por que o mundo o rejeita. A fome de quem nunca recebeu nada que não fosse mais fome. Era um ódio que não tinha nascido de si mesmo: tinha sido alimentado, a vida inteira, por todos os que, como ele agora, a tinham combatido.",
      "Ele a reconheceu.",
      "Não de lugar nenhum. Não de lembrança nenhuma. De dentro. Era a mesma coisa que ele tinha sentido na manhã em que o corpo falhou. A mesma coisa que rugira dentro dele quando a cadeira de Kassandra ficou vazia.",
      "— Eu conheço você — disse Barnabé, baixinho.",
      "E a sombra, pela primeira vez, hesitou.",
      "Ele olhou para a espada, a espada que dois tinham feito com tanto cuidado, e entendeu o que ela nunca poderia ensinar: que vencer aquilo não era cortar. Que cada corte alimentava.",
      "Abriu a mão.",
      "A espada voou, girando, e fincou-se na terra a dez passos dali, de pé, zunindo, uma fenda de luz no meio da clareira.",
      "E Barnabé correu.",
      "Correu de peito aberto, sem defesa nenhuma, como nunca correra em batalha. Correu direto para dentro dela. O medo que o grito tinha espalhado ainda segurava todo mundo no lugar, e ninguém viu o ogro fazer a coisa mais corajosa que alguém jamais tinha feito naquela floresta: ele abraçou a sombra.",
      "Os braços enormes se fecharam em volta do escuro. O frio entrou por cada poro. E, com as lágrimas descendo — lágrimas de alegria, que só ele sabia por quê, e que nunca contaria a ninguém —, Barnabé deu a ela tudo o que tinha.",
      "Todo o amor. Toda a compreensão. Toda a paciência que nenhum ser humano jamais tinha sido capaz de ter por uma criatura como aquela, e que ele, ogro, que passara a vida sendo chamado de monstro, tinha de sobra.",
      "— Eu sei — murmurou. — Eu sei. Eu sei como é.",
      "A sombra parou de se mexer.",
      "Depois começou a se sentir estranha. Tentou se desvencilhar, e não conseguiu. Contorceu-se, como quem tenta cuspir um alimento que não conhecia. Recuou, e recuou, e dentro dela, aos poucos, fios de luz começaram a sair — finos, depois mais grossos — rasgando o escuro por dentro, saindo pelos olhos que ela não tinha, pela boca que ela não tinha, pelo peito.",
      "Ela explodiu em luz.",
      "Uma luz branca, limpa, tão forte que a clareira inteira desapareceu dentro dela. Quando enfim se apagou, onde tinha estado a sombra havia uma silhueta transparente, feita de claridade.",
      "Um lobo. Branco, enorme, de olhos serenos.",
      "Ele olhou para Barnabé. Inclinou a cabeça, devagar, num gesto que só podia significar obrigado.",
      "E sorriu.",
      "Depois evaporou, no meio do ar, como o último resto de neblina quando o sol sobe.",
      "O medo se foi com ele. Os pássaros voltaram a voar. A raposa pousou a pata. Arquimendes caiu de joelhos, com o coração batendo na garganta.",
      "O tempo voltou a Barnabé de uma só vez.",
      "A barba embranqueceu. As costas curvaram. O joelho estalou, o ombro travou, e o ogro, que há um minuto era o maior guerreiro do mundo, caiu sentado na terra, velho outra vez, rindo e chorando sem conseguir parar.",
      "Arquimendes correu até ele.",
      "— O senhor está— O que foi isso? O que o senhor fez?",
      "— Não sei — disse Barnabé, enxugando o rosto com as costas da mão enorme. — Mas ele era só faminto.",
      "— Faminto de quê?",
      "— De ser visto, acho. — O ogro olhou para o céu limpo. — Ou de ser abraçado. Não sei dizer qual dos dois.",
      "Arelah veio andando pela clareira, devagar, os pezinhos descalços na terra. Parou diante dele, olhou o ogro caído, o velho de sempre, e abriu os braços o mais que podia.",
      "— Alá — disse.",
      "Ele a levantou para o colo, como quem pega a coisa mais frágil e mais forte do mundo.",
      "A espada ficou fincada na terra até o amanhecer. Quando o sol subiu, a lâmina se apagou, como se tivesse cumprido o que lhe cabia, e restou só o cabo, com a letra dela, e o desenho do cachimbo.",
      "Naquela noite, pela primeira vez em nove, ninguém dormiu sentado.",
    ],
    fragmentoProfecia:
      "O que o ódio alimenta, a espada não vence: só o abraço dissolve. E toda sombra desfeita devolve a luz que guardava.",
  },
];

export function getCapitulo(numero: number): Capitulo | undefined {
  return capitulos.find((c) => c.numero === numero);
}
