export type Capitulo = {
  numero: number;
  titulo: string;
  subtitulo: string;
  /** Ilustração própria do capítulo. */
  imagem?: string;
  /** Índice da cena 3D de fundo, reaproveitando o mesmo sistema dos poemas. */
  cena: number;
  paragrafos: string[];
  /** Fragmento da profecia revelado ao final do capítulo — sem explicação. */
  fragmentoProfecia: string;
};

/** Arte de capa do livro (viajante diante do rosto de estrelas). */
export const IMAGEM_CAPA = "/assets/images/arelah-capa.webp";

export const capitulos: Capitulo[] = [
  {
    numero: 1,
    titulo: "Arelah — Origens",
    subtitulo: "O dia que nasceu o Infinito",
    imagem: "/assets/images/arelah-cap1.webp",
    cena: 2,
    paragrafos: [
      "Ela tinha um mundo só dela.",
      "A língua era diferente, os sons eram diferentes, e a magia existia mais forte nela do que na própria terra ao seu redor. O sol era quente porque Arelah era sorridente, a vida existia porque ela era feliz. Não era Arelah que ficava triste quando o mundo estava cinza — era o mundo que ficava cinza quando ela estava triste. Mas essa palavra nunca tinha entrado no vocabulário dela antes. Era só um mito. Até que um dia virou fato.",
      "Mas esse capítulo não é sobre isso.",
      "Talvez fosse sobre como Arquimendes conheceu Kassandra — não que alguém tivesse pedido pra contar, mas as histórias insistem em vir à tona quando menos se espera.",
      "Ele era um inventor sem inventos que funcionassem ainda, vivendo de promessas e resto de metal, quando a viu pela primeira vez: descalça, ajoelhada numa vala entre pedras, plantando algo que ninguém mais teria coragem de tocar. Ele perguntou o que era. Ela não respondeu — só olhou pra ele do jeito que olhava pras plantas, como quem decide, em silêncio, se vale a pena cuidar daquilo.",
      "Decidiu que valia.",
      "Ele voltou no dia seguinte com uma ferramenta que ela não tinha pedido. E no outro. E no outro, até virar hábito, e o hábito virar necessidade, e a necessidade virar a única coisa entre os dois que nunca precisou de explicação.",
      "Se amavam tão fervorosamente que os astros se alinhavam pra contemplar o ato — não porque alguém tivesse escrito isso em algum lugar, mas porque era simplesmente verdade, do jeito que certas verdades são, sem precisar de testemunha.",
      "Foi Kassandra quem trouxe a planta daquela mesma vala de pedras — anos antes, muito antes de Arelah, muito antes até do próprio Arquimendes. Ninguém mais se aproximava daquele lugar; diziam que era ruína de gente que não existia mais em nenhum mapa. Ela não perguntou por quê. Só cavou, embrulhou a raiz num pano úmido, e levou pra casa como quem resgata algo abandonado.",
      "A planta — ela chamava de sibannac, sem saber ao certo onde tinha aprendido o nome — florescia todo santo dia às 16:20, pegava fogo por conta própria, e se apagava sozinha minutos depois, deixando um cheiro que ninguém sabia descrever direito. Kassandra nunca perguntou por quê. Achava bonito demais pra questionar.",
      "Só sabia de uma coisa, sem saber explicar: perto da sibannac, era como se uma parte dela — aquela parte que sempre sentia as coisas antes de vê-las — ficasse em silêncio. Um silêncio bom, ela achava. Um descanso.",
      "Nunca soube que era outra coisa.",
      "Era 22 de setembro da era π. Ela completava 2 anos e 2 meses.",
      "Uma coincidência que ninguém naquela casa havia notado.",
      "Naquela noite, Arelah não falava. Só apontava coisas.",
      "Mas seus olhos estavam fixos na bolha d'água que pairava em pleno ar — rodando em torno de si mesma, lenta, perfeita, como um planeta minúsculo que havia decidido existir ali, entre a lareira e a mesa de jantar. Ela não sabia que aquilo era extraordinário. Pra ela era tão natural quanto respirar.",
      "Do outro lado da mesa, Arquimendes desenhava plantas de algo que provavelmente nunca seria construído. Kassandra organizava os potes sem olhar, como quem executa uma memória antiga.",
      "Ninguém via. Cada um no seu mundo — quando de repente.",
      "PLAAAAAAA.",
      "A porta bateu com uma força que não combinava com ninguém que quisesse apenas visitar. A bolha d'água desapareceu em poça no chão de terra batida. Arelah virou a cabeça devagar, sem susto — como se soubesse quem era antes de ver.",
      "Na entrada, com o cachimbo apagado entre os dentes e a muleta encostada na parede que acabara de estremecer, estava Barnabé.",
      "— Kassandra! — gritou ele, como se ela estivesse do outro lado de uma montanha. — A maldita planta floriu hoje? Preciso acender esse troço!",
      "Ninguém olhou pro chão.",
      "Ninguém viu a poça.",
      "Só Arelah — que apontou pra ela, depois apontou pra Barnabé, e fez algo que nunca havia feito antes.",
      "Sorriu.",
    ],
    fragmentoProfecia:
      "No dia em que o quatro encontrou o quatro, nasceu o que não tem fim. Ninguém contou os dias que passaram até ali. Ninguém precisava — o infinito não se soma, se repete.",
  },
  {
    numero: 2,
    titulo: "Arelah — Origens",
    subtitulo: "O Fim do Começo",
    imagem: "/assets/images/arelah-cap2-v2.webp",
    cena: 0,
    paragrafos: [
      "Barnabé entrou sem ser convidado — como sempre fazia.",
      "Mas o cachimbo continuava apagado. E a criança no chão não tirava os olhos dele desde que a porta batera — um jeito de olhar que ele não lembrava de ter visto antes, nem em campos de batalha.",
      "Kassandra, que não aceitava desaforos nem da própria sombra, cresceu como gigante em poderio. E antes de mais um passo, Barnabé — velho de guerra, sobrevivente de batalhas que ninguém mais lembrava — sentiu o frio na espinha. Entendeu, naquele instante, que desafiar aquela mulher era pior do que qualquer inimigo encontrado nos exércitos mais ferozes do passado.",
      "— Pare aí mesmo. Eu limpei a casa hoje — veja lá se isso são modos, seu ogro sem educação.",
      "Num instante, Barnabé perdeu toda a compostura. O velho de guerra encolheu como filhote de gatinho perto da lareira.",
      "— Sim, senhora dona Kassandra. Eu só queria mesmo saber se o foguinho deu certo. Estou precisando fumar. — Fez uma pausa, olhou pro chão, e apontou com a muleta. — Percebi que a senhora limpou a casa. Estava terminando de secar?",
      "Kassandra perdeu o tamanho gigantesco que a raiva lhe dera e se virou para a tal poça de água, olhando-a com uma ruga funda entre as sobrancelhas — de onde tinha vindo aquilo? Mas antes que o pensamento terminasse de se formar, uma máquina voadora mecânica cortou o ar vinda do quarto de Arquimendes, passou zunindo pela sala e foi se estatelar na parede do fundo.",
      "Kassandra olhou pra máquina. Olhou pra poça. Olhou pro quarto.",
      "Seu rosto ficou vermelho.",
      "— ARQUIMENDES, não acredito que você—",
      "— EUREKAAAAAAAAA!",
      "A voz dele explodiu antes que ela terminasse.",
      "Arquimendes saiu do quarto como se o mundo inteiro precisasse saber da notícia.",
      "— Finalizei! O coletor de partículas! Se eu estiver certo — e eu estou — com isso poderemos alimentar o gerador de energia para sempre!",
      "Kassandra respirou fundo. Pegou um pedaço de guantchale da mesa. Mordeu. Bocejou.",
      "— Claro, claro, claro. Só falta um pequeno detalhe, não é meu amor?",
      "— Qual?",
      "— Precisa funcionar.",
      "Arquimendes nem ouviu. Já tinha Barnabé pelo colarinho e o arrastava porta afora.",
      "— Venha, venha, venha — precisamos instalar no telhado. Agora.",
      "— Espere, espere — gritou Barnabé sendo arrastado — é mais seguro apoiar do outro lado, eu conheço estruturas, eu já vi casas—",
      "— Só segure a escada, seu velho falastrão.",
      "A casa de Arquimendes era um organismo vivo.",
      "Cabos percorriam as paredes como veias — entravam e saíam pelas raízes e frestas, carregando um fluxo de extratos de plantas escolhidos por Kassandra e energia gerada pelas engenhocas de Arquimendes. Cinco invenções fracassadas pra cada uma que funcionava. Sucata empilhada em cada canto. Papéis com anotações, sonhos e esquemas espalhados por todos os cômodos. Era impossível dizer onde terminava a casa e onde começavam as invenções.",
      "No centro de tudo isso — Arelah.",
      "Quieta. Observando. Rindo de coisas que ninguém mais via.",
      "Kassandra voltou com o balde, o pano e a água. Começou a limpar a poça de costas para a filha.",
      "Lá fora, Barnabé segurava a escada e discutia cada degrau enquanto Arquimendes subia escorregando, ignorando cada aviso com a confiança de quem nunca caiu — ainda.",
      "No topo, Arquimendes fez os últimos ajustes. Respirou fundo. Preparou-se para encaixar a peça final no capacitor translucidérico temporalmetildo convexso.",
      "Dentro, Arelah sentiu o vento.",
      "E o cheiro de chuva que ela tanto amava.",
      "O arrepio do clima a animou — ela também queria brincar na água. Lembrou da bolha. E instantaneamente, toda a água do balde de Kassandra voltou ao ar — rodando em torno de si mesma, perfeita, como um planeta que havia decidido existir ali de novo.",
      "Deu um gritinho tímido.",
      "— Alá.",
      "Kassandra sorriu sem virar.",
      "— Vai chover, minha princesinha. Está com fome?",
      "Virou-se devagar para ver a resposta da filha.",
      "E emudeceu.",
      "A cor saiu completamente do seu rosto.",
      "O silêncio durou exatamente o tempo de um raio decidir onde cair.",
      "KABLAN.",
      "O trovão cortou tudo ao mesmo tempo — o espanto de Kassandra, o grito de Barnabé lá fora, e o braço estendido de Arquimendes no momento exato em que encaixava a peça no capacitor.",
      "O raio o atingiu.",
      "A invenção conectou.",
      "Às 16:20, a sibannac floriu — e pegou fogo, como fazia todos os dias, naquele mesmo horário de sempre.",
      "A faísca encontrou os cabos. Os cabos encontraram os extratos. Os extratos encontraram a energia. A energia encontrou o raio. O raio encontrou a magia de Arelah no ar.",
      "E tudo — absolutamente tudo — se conectou na explosão.",
      "O tempo parou.",
      "Não desacelerou. Não hesitou.",
      "Parou.",
      "Barnabé congelou no meio de um grito. Kassandra congelou com a boca aberta e os olhos arregalados. Arquimendes congelou no telhado — iluminado, os cabelos em pé, uma expressão entre o êxtase e o terror.",
      "Só Arelah se movia.",
      "Atravessou a sala em câmera lentíssima — milissegundos que pareciam horas. Tocou os cacos que voavam sem chegar ao destino. Passou pelos fios de energia suspensa no ar como cortinas de luz. Cheirou a fumaça da sibannac que subia em espiral congelada.",
      "Para ela era um parque de diversões.",
      "Ela não sabia o que era uma explosão. Não sabia o que era o perigo. Não sabia o que era o tempo parando.",
      "Só sabia que aquelas cores eram bonitas. E que o cheiro de chuva ainda estava lá.",
      "Andou. Sorriu. Foi indo.",
      "Até chegar lá fora.",
      "E olhar.",
      "O cogumelo gigante de destruição subia lento e majestoso onde havia sido a sua casa — uma devastação completa, suspensa no tempo como uma pintura do fim do mundo.",
      "Arelah inclinou a cabeça.",
      "Apontou.",
      "E riu.",
    ],
    fragmentoProfecia:
      "O que parece o fim é só o começo, dobrado sobre si mesmo — como tudo que é infinito faz, quando alguém demora demais pra perceber que está olhando.",
  },
  {
    numero: 3,
    titulo: "Arelah — Origens",
    subtitulo: "Os Três Que Ficaram",
    imagem: "/assets/images/arelah-cap3.webp",
    cena: 1,
    paragrafos: [
      "O tempo levou um instante para lembrar como se mover.",
      "Não voltou de uma vez. Voltou em pedaços — primeiro o som, depois o cheiro, depois, por último, o peso das coisas que precisam cair.",
      "A nuvem em forma de cogumelo, que até então pairava congelada sobre os escombros, desabou sobre si mesma em silêncio, como se também estivesse exausta. Poeira. Fumaça. Um cheiro doce e queimado que não vinha só da madeira.",
      "Da sibannac, só restava cinza — e o que quer que aquela fumaça fizesse, já tinha feito.",
      "Barnabé foi o primeiro a se mexer — reflexo de quem passou a vida inteira aprendendo a se levantar antes de entender por quê.",
      "— Posição! — berrou, a voz rouca de comando, antes mesmo de abrir os olhos direito. — Todo mundo no chão, cabeça baixa, já!",
      "Ninguém se abaixou. Ele mesmo parou no meio do próprio grito, a muleta tremendo sob o peso, porque não fazia a menor ideia de que guerra estava tentando vencer, nem onde tinha aprendido a gritar daquele jeito.",
      "— Que... — murmurou, baixando o tom, olhando a própria mão como se ela pertencesse a outra pessoa. — Que diabos eu tava dizendo?",
      "Kassandra ergueu a cabeça da poça que limpava — ou tentava limpar, antes do mundo explodir — e cravou os olhos nele com a mesma dureza de sempre, quase por costume.",
      "— Fala baixo perto da criança.",
      "A ordem saiu antes de qualquer pensamento, pronta, como se sempre tivesse estado ali, só esperando pra ser usada. Barnabé fechou a boca na hora — e só depois os dois perceberam o que tinha acabado de acontecer: ela dera uma ordem a um homem cujo rosto mal reconhecia, e ele tinha obedecido sem questionar, do jeito que se obedece há anos.",
      "— Kassandra — disse ele, baixinho, testando o nome na boca como quem experimenta uma roupa emprestada. — É esse o seu nome, não é?",
      "— É. — Ela não perguntou como ele sabia. Sabia o dele também, Barnabé, sem lembrar de nenhuma conversa em que tivesse aprendido.",
      "Do que sobrou do telhado, Arquimendes escorregou mais do que desceu, aterrissando sentado no meio do entulho — e, antes de qualquer outra coisa, antes até de respirar fundo, esticou o braço pra examinar a própria mão chamuscada.",
      "— Fascinante — sussurrou, virando o pulso contra a luz. — A descarga passou pelo capacitor, pela planta, por mim... e eu continuo inteiro. Isso devia ser estudado.",
      "Só quando ergueu os olhos do próprio braço é que percebeu os outros dois olhando pra ele. E só então chegou a pergunta — atrasada, incômoda, maior que qualquer invenção: quem eram aquelas pessoas, e por que o peito doía de um jeito que não tinha nada a ver com física?",
      "— Eu... — começou, e não achou fim pra frase.",
      "— Arquimendes — disse Kassandra, antes que ele terminasse de não terminar. Não era pergunta.",
      "Ele assentiu, devagar, sem saber explicar por que aquele nome soava certo na boca dela, e estranho em qualquer outra.",
      "Os três ficaram ali, parados entre os escombros — três pessoas que se conheciam havia exatamente um minuto e meio, e que, ao mesmo tempo, carregavam entre si uma vida inteira que nenhum conseguia alcançar.",
      "Ninguém perguntou mais nada. Não havia pergunta que coubesse no tamanho daquele silêncio.",
      "Foi Arelah quem o quebrou.",
      "Sentada no meio do que sobrou do quintal, cercada de cacos e fumaça, ela esfregou os olhos como quem acorda de um cochilo comprido. Não parecia assustada. Parecia, se é que a palavra serve pra uma criança daquela idade, satisfeita.",
      "Os três adultos se viraram pra ela ao mesmo tempo.",
      "Foi Kassandra quem se moveu primeiro — não devagar, não com cautela, mas do jeito que se corre até quem se ama, sem pensar duas vezes. Ajoelhou na poeira ao lado da menina e passou a mão pelo cabelo dela antes mesmo de decidir fazer isso.",
      "— Você tá bem? — A voz saiu rachada, cheia de um carinho que não tinha explicação nenhuma pronta.",
      "Arelah só sorriu e apontou pra fumaça, como quem mostra um brinquedo novo.",
      "Arquimendes se aproximou mancando de leve, o cabelo ainda fumegando nas pontas, e abaixou até ficar da altura dela. Não disse nada sobre física dessa vez. Só olhou — com o mesmo espanto de quando tinha visto a descarga atravessar o próprio braço, só que maior.",
      "Barnabé ficou de pé, apoiado na muleta, um passo atrás dos outros dois. Vinha de uma vida inteira sabendo reconhecer a hora de recuar e deixar os outros chegarem perto — e sabia, sem saber como sabia, que aquele era um desses momentos.",
      "Mas também sabia outra coisa, mais funda que qualquer lembrança perdida: tinha acabado de ver aquela criança parar o tempo com as próprias mãos. Tinha visto ela devolver uma tempestade inteira pro céu de onde tinha vindo. E fosse o que fosse aquilo — soldado nenhum, por mais memória que tivesse perdido, ficaria de costas pra uma coisa daquele tamanho.",
      "Não porque fosse filha de alguém.",
      "Porque era ela.",
      "Ninguém falou sobre reconstruir a casa. Ninguém falou sobre nomes direito, sobre quem amava quem, sobre o que cada um tinha sido antes daquela noite. Isso viria depois, devagar, do jeito que se aprende uma língua nova: tentando, errando, repetindo.",
      "O que ficou decidido, sem que ninguém precisasse dizer em voz alta, foi mais simples que tudo isso: continuariam ali. Juntos. Por ela.",
      "Longe dali — muito mais longe do que qualquer um daqueles três conseguiria imaginar — o céu tinha se partido ao meio.",
      "Um feixe de luz sem cor definida cruzou a noite na direção contrária à de todas as estrelas, como se tivesse pressa de chegar a algum lugar que ainda não existia. Atravessou nuvens que não deviam estar ali. Acendeu, por um segundo e meio, três sóis que há eras não nasciam ao mesmo tempo. Dobrou uma tempestade inteira sobre si mesma e a jogou pra outro lugar — nenhum mapa registraria pra onde.",
      "A cinco constelações de distância, não houve um único olho, broto ou coração que não sentisse alguma coisa se mexer.",
      "Ninguém saberia dizer o quê. Ninguém saberia dizer de onde. Mas todos, de um jeito ou de outro, pararam o que estavam fazendo por um instante — e sentiram, fundo, que algo que não devia existir tinha acabado de nascer.",
      "Em algum lugar, alguém ergueu a cabeça.",
      "E começou a procurar.",
    ],
    fragmentoProfecia:
      "O que nasce do fim não escolhe os pais que lhe restam — escolhe quem fica. E quem fica, de um jeito ou de outro, será encontrado.",
  },
  {
    numero: 4,
    titulo: "Arelah — Origens",
    subtitulo: "A Casa de Três Tempos",
    imagem: "/assets/images/arelah-cap4.webp",
    cena: 0,
    paragrafos: [
      "Levaram vinte e três dias para o telhado voltar a ser telhado.",
      "Kassandra contava os dias em tábuas. Uma tábua pregada, um dia vivido — era o único calendário que ainda fazia sentido pra quem não tinha ontem pra comparar.",
      "A floresta em volta não perguntava nada. Ninguém passava por ali, ninguém via a fumaça, ninguém ouvia as marteladas. Era um esconderijo que nenhum deles tinha escolhido — e talvez por isso funcionasse.",
      "Arquimendes passou a primeira semana revirando os papéis que o fogo poupou. Eram dezenas: esquemas, cálculos, rabiscos nas margens, tudo numa letra apertada e nervosa que ele só reconhecia como sua porque não havia mais ninguém ali que escrevesse.",
      "— Esse sujeito é um gênio ou um idiota — anunciou, sacudindo uma folha no ar. — Ainda não decidi.",
      "— Decida enquanto carrega as vigas — respondeu Kassandra, sem erguer os olhos dos potes.",
      "Ele carregou. Mas à noite voltava aos papéis, lia as próprias ideias como quem escuta um desconhecido muito interessante, e discutia em voz baixa com a margem das folhas.",
      "Os potes, Kassandra nem precisava olhar. As mãos sabiam onde cada um morava — o de raízes à esquerda, o de sal no alto, o de cinzas azuis atrás — e se enganavam só quando a cabeça tentava ajudar. Descobriu depressa que funcionava melhor deixando de pensar.",
      "Da sibannac sobrara uma raiz. Escura, torta, enterrada no meio da cinza como se tivesse decidido esperar.",
      "Ela a replantou sem saber por quê. No terceiro dia veio um broto. No décimo, uma flor. E às 16:20 em ponto a flor pegou fogo sozinha, se apagou sozinha, e deixou aquele cheiro que ninguém sabia descrever.",
      "Kassandra anotou a hora num pedaço de casca. Depois anotou outra coisa, que não contou a ninguém: perto da planta, o zumbido que ela nem sabia carregar na cabeça ficava quieto. Um descanso.",
      "Nunca soube que era outra coisa.",
      "Barnabé, por sua vez, tinha decidido que não adiantava ficar sentado esperando uma lembrança chegar de visita.",
      "Levantava antes do sol, pendurava a muleta num galho e se plantava no meio da clareira — pés afastados, ombros baixos, o peso inteiro na terra. Não sabia por que aquela postura. Só sabia que o corpo ficava mais honesto assim.",
      "Depois vinham os movimentos. Um passo, uma virada, um golpe de braço que cortava o ar de um jeito que não era de lenhador. Lento no começo. Cada manhã um pouco menos lento.",
      "— O senhor sempre acordou com esse humor? — perguntou Kassandra uma vez, da porta, com a caneca na mão.",
      "— Não faço ideia, dona Kassandra. — Ele nem parou. — Mas esse tronco aqui me deve satisfações.",
      "Nenhum dos três perguntava por que treinava, estudava ou plantava. Faziam. Como quem arruma a casa antes da visita — sem saber quem vem.",
      "E no meio disso tudo, Arelah.",
      "Arelah apontava.",
      "Apontava pro balde, pro passarinho, pras mãos da mãe mexendo nos potes. E dizia a única palavra que tinha:",
      "— Alá.",
      "Alá pro fogo. Alá pro barulho do martelo. Alá pro vazio entre duas árvores, onde ninguém via nada. Era uma palavra que servia pra tudo, e talvez por isso ninguém duvidasse de que significava alguma coisa.",
      "Foi na segunda semana que aconteceu pela primeira vez.",
      "Ela estava sentada no chão da sala, diante da bacia de madeira onde a água esperava ser levada pro poço. Apontou. Disse seu alá, baixinho. E parou.",
      "Não dormiu. Não distraiu. Os olhos continuaram abertos, mas já não estavam ali — fixos em lugar nenhum, num ponto onde o mundo parecia dobrar.",
      "A bacia envelheceu.",
      "Os aros racharam, a madeira escureceu, o limo subiu pelas bordas como uma maré lenta. Em seguida desfez o caminho: o limo recuou, as rachaduras se fecharam, a madeira ficou clara e cheirando a serra recém-passada. Mais um instante e era só um tronco, depois só uma semente, depois — por um segundo que ninguém soube contar — nada.",
      "Então voltou a ser bacia.",
      "Kassandra ficou parada com o pano na mão. Arquimendes soltou o papel. Barnabé, na porta, esqueceu a muleta no ombro.",
      "— Ela fez isso — disse Arquimendes, baixinho, com a voz de quem vê o próprio invento funcionar sem ter apertado nada.",
      "— Ela está bem — disse Kassandra, e não era pergunta, era ordem para o universo.",
      "Arelah piscou. Voltou. Sorriu pros três, satisfeita, como quem acabou de ver um bicho bonito passar.",
      "— Alá — disse.",
      "Ninguém a repreendeu. Ninguém sequer pensou em repreender. Eles tinham visto o dia em que ela parou o tempo; uma bacia que ia e voltava parecia, comparada a isso, quase um jeito educado de brincar.",
      "O que sentiram foi outra coisa: a certeza de que aquilo precisava de cuidado, não de medo.",
      "— Ela não sabe o que está fazendo — observou Arquimendes.",
      "— Ninguém aqui sabe — rebateu Kassandra. — Então vamos descobrir juntos.",
      "Sentou-se no chão, na frente da menina, e pegou as mãozinhas dela entre as suas.",
      "— Respire comigo. Devagar. Não olhe pro nada, olhe pra mim. É pra mim que você aponta, tá? Aponta aqui.",
      "Arelah apontou o nariz da mãe, deu uma gargalhada, e a bacia atrás delas deu um estalo, só um, e ficou como estava.",
      "Kassandra olhou pros outros dois, vitoriosa.",
      "— Funcionou. Mais ou menos.",
      "— Em batalha — disse Barnabé, apoiando o peso na muleta — a gente aprende a segurar a espada sem apertar. Quem aperta, treme. Quem solta, perde. É um meio-termo, tipo segurar um passarinho.",
      "— Ela não tem espada — disse Arquimendes.",
      "— Tem o que tem — respondeu o ogro, dando de ombros que faziam sombra. — O princípio é o mesmo.",
      "Era um conselho que nenhum dos três sabia de onde vinha. Funcionava mesmo assim.",
      "Foi assim que a rotina mudou. De manhã Arquimendes ajeitava vigas e a menina o observava; à tarde, Barnabé ensinava a respirar, a soltar, a segurar um passarinho com a ponta da atenção; à noite, Kassandra sentava com ela perto da sibannac e esperava a flor pegar fogo, e a magia de Arelah ficava mansa, como bicho que dorme encostado em outro.",
      "E aos poucos a casa foi voltando.",
      "Mas voltando diferente.",
      "A parede norte subiu intacta, lisa, com o reboco que tinha antes da explosão — Arquimendes jurava nunca ter feito aquilo. A parede sul continuou do jeito que o fogo a deixara: escura, rachada, cheirando a fim. E a parede leste, a que não deveria existir ainda, apareceu certa manhã coberta de hera velha, com uma janela de moldura que nenhum deles tinha desenhado.",
      "— De quando é essa parede? — perguntou Kassandra, passando a mão na pedra fria.",
      "Ninguém soube responder.",
      "O passado, o presente e o que ainda estava por vir tinham se encontrado ali e decidido, de comum acordo, dividir o mesmo teto.",
      "Eles não se assustaram. Já não era possível se assustar de uma casa depois de ver o que se vira.",
      "Numa noite sem lua, quando a menina enfim dormia, Kassandra e Arquimendes ficaram sozinhos junto ao fogo. Sentados perto demais, longe demais, sem saber qual dos dois.",
      "— Eu não sei se eu amava você — disse ela, olhando as brasas. — Queria dizer isso em voz alta, só pra não carregar sozinha.",
      "— Eu também não sei — respondeu ele, sem ofensa nenhuma, com a mesma curiosidade com que lia seus esquemas. — Mas sei que, se você saísse por aquela porta, eu iria atrás.",
      "— Isso não é amor. Pode ser dever.",
      "— Pode ser. — Ele sorriu, torto. — Mas se eu não lembrasse de nada, eu iria atrás de você sempre!",
      "Ela não respondeu. Mas não se afastou.",
      "Lá fora, na clareira, Barnabé fazia a última ronda da noite, a muleta pendurada, o passo mais firme do que o de alguém que não se lembrava de por que andava assim.",
      "Não sabia ainda — nenhum deles sabia — que cada manhã de treino o preparava para um dia que se aproximava de passos lentos, e que esse dia exigiria dele muito mais do que postura.",
      "Longe dali — longe o bastante para que o vento esquecesse o nome de quem soprava — algo parou no meio de uma estrada.",
      "Sentiu.",
      "Foi pouco. Uma dobra de ar. Um eco de bacia que envelhece e rejuvenesce no mesmo instante. Mas era o bastante: pela primeira vez desde a noite em que o céu se partira, o rumo deixou de ser um palpite e virou um cheiro.",
      "Cada magia que a menina fazia acendia uma luzinha. E cada luzinha era um pouco mais fácil de seguir do que a anterior.",
      "Atrás da casa de três tempos, no escuro, uma criança dormia com um sorriso pequeno, e na boca, mesmo no sono, a única palavra que sabia:",
      "— Alá.",
    ],
    fragmentoProfecia:
      "Quem dobra o tempo não o esconde — deixa dobras. E toda dobra é um caminho, para quem souber seguir o vinco.",
  },
];

export function getCapitulo(numero: number): Capitulo | undefined {
  return capitulos.find((c) => c.numero === numero);
}
